language: csharp
solution: TamGiac.sln
os: windows
install:
  - nuget restore TamGiac.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug TamGiac.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe  ./TamGiac.Test/bin/Debug/TamGiac.Test.dll